# Generated by Django 3.2 on 2024-02-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/7c1e6701-8332-4231-8551-fc27c2636963/'),
        ),
    ]
