# Generated by Django 3.2 on 2024-02-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/0392dc2f-381a-40c7-9975-a0a217cbdf19/'),
        ),
    ]
