# Generated by Django 3.2 on 2024-08-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/3c1e4e2b-4bbb-4383-a201-fb37d5ae7bfc/'),
        ),
    ]
