# Generated by Django 3.2 on 2024-08-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/2a3c14b6-15c2-4bba-bb0c-a6db89cad2c3/'),
        ),
    ]
