# Generated by Django 3.2 on 2024-08-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/a2c45fbc-4408-40c6-91ad-a45d841b820d/'),
        ),
    ]
