# Generated by Django 3.2 on 2024-08-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/cfc0011d-91c8-49a6-b9b0-72e5dbd69ca8/'),
        ),
    ]
