# Generated by Django 3.2 on 2024-08-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/f13012f1-fdde-4d02-b6f3-db9f9b8840c5/'),
        ),
    ]
