# Generated by Django 3.2 on 2024-08-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/4b50f296-91d6-4068-a8bb-8b87ec8e2cc9/'),
        ),
    ]
