# Generated by Django 3.2 on 2024-08-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/a14f744c-0ec7-4166-bdb5-c28ac61521dd/'),
        ),
    ]
