# Generated by Django 3.2 on 2024-08-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/2c5f9ef5-ba00-485b-9858-3f0cc4e22245/'),
        ),
    ]
