# Generated by Django 3.2 on 2024-08-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/cfc87494-7575-4c28-804d-1d710d706bd3/'),
        ),
    ]
