# Generated by Django 3.2 on 2024-08-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/b3ee5aa0-39e8-43c7-ae5d-4b23def8bf58/'),
        ),
    ]
