# Generated by Django 3.2 on 2024-08-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/d0e05eba-f21c-4094-afd1-6210864d1ad9/'),
        ),
    ]
