# Generated by Django 3.2 on 2024-08-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/ca3347f6-07e5-4f6e-872d-89a53e4e642a/'),
        ),
    ]
