# Generated by Django 3.2 on 2024-08-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/8698aa0c-12a4-4ffc-a3dd-00c1e444dddc/'),
        ),
    ]
