# Generated by Django 5.1 on 2024-08-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/0dd7d412-886e-4bb9-8d73-2be30e31b90e/'),
        ),
    ]
