# Generated by Django 5.1 on 2024-08-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/02614433-0316-4736-8833-17c8ec6c8c0f/'),
        ),
    ]
