# Generated by Django 5.1 on 2024-09-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/9ef6b1cd-826f-41e0-b351-e98664379fdc/'),
        ),
    ]
