# Generated by Django 5.1 on 2024-09-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0037_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/11a815e4-7d7e-4513-abe3-0861c1c92319/'),
        ),
    ]
