# Generated by Django 5.1 on 2024-09-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0039_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/d310363e-d2ed-4b06-bda5-a37aa614ad67/'),
        ),
    ]
