# Generated by Django 5.1 on 2024-09-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0040_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/a0c501f1-c68f-43cd-8e1e-624fca0d4d26/'),
        ),
    ]
