# Generated by Django 5.1 on 2024-09-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0041_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/ebb90e00-da4f-472c-a9ba-7809b2b02298/'),
        ),
    ]
