# Generated by Django 5.1 on 2024-09-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0043_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/e69ac15c-c925-460a-97d1-053d03e6362f/'),
        ),
    ]
