# Generated by Django 5.1 on 2024-09-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0045_alter_myuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='num_bid',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/2d4b1b9f-67bc-4381-be97-79abc88a843f/'),
        ),
    ]
