# Generated by Django 5.1 on 2024-09-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0046_myuser_bider_myuser_num_bid_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/9e635ddb-f862-4883-9e40-7d2fe8644a42/'),
        ),
    ]
