# Generated by Django 5.1 on 2024-09-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0048_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/160ad99e-328f-4c85-89e5-4fdf40fd7b97/'),
        ),
    ]
