# Generated by Django 5.1 on 2024-09-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0052_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/06765ae3-bc78-43df-a96b-48604740a13d/'),
        ),
    ]
