# Generated by Django 5.1 on 2024-09-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0054_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/cb879840-4063-4a6d-9709-0ef750cd5276/'),
        ),
    ]
