# Generated by Django 5.1 on 2024-09-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0055_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/925c127a-fb36-4c68-96d0-ceda53cdb6f5/'),
        ),
    ]
