# Generated by Django 3.2 on 2024-09-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0056_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/dd84af3d-89a4-4ead-8bc3-2b7c4ad0bfe6/'),
        ),
    ]
