# Generated by Django 3.2 on 2024-09-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0057_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/e714579a-8eb2-4df0-9b38-5312f1f6a8a0/'),
        ),
    ]
