# Generated by Django 3.2 on 2024-09-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0059_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/98875e4d-626e-44d9-85ea-57d8a1d0c52d/'),
        ),
    ]
