# Generated by Django 5.1 on 2024-09-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
