# Generated by Django 3.2 on 2024-09-23 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_remove_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalogue.category'),
        ),
    ]
