# Generated by Django 3.2 on 2024-02-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
    ]
