# Generated by Django 3.2 on 2024-02-25 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_remove_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='customer',
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='location', to='login.myuser'),
            preserve_default=False,
        ),
    ]
