# Generated by Django 3.2 on 2024-02-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_location_codeposti'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='family',
            field=models.CharField(default=1, max_length=48),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='mobile',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
