# Generated by Django 3.2 on 2024-08-12 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20240812_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='my_shop',
        ),
    ]
