# Generated by Django 3.2 on 2024-08-12 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_product_my_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='my_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.myshop'),
            preserve_default=False,
        ),
    ]
