# Generated by Django 5.1 on 2024-09-09 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_my_shop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.RenameField(
            model_name='basketline',
            old_name='Product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='location',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myshop',
            name='image',
            field=models.ImageField(upload_to='shops/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='shop.invoice'),
        ),
    ]
