# Generated by Django 5.1 on 2024-09-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.TextField(unique=True),
        ),
    ]
