# Generated by Django 3.2 on 2024-10-08 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_sub_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={},
        ),
    ]
