# Generated by Django 3.2 on 2024-08-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/transport/car/'),
        ),
    ]
