# Generated by Django 3.2 on 2024-08-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20240815_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='pelak',
            field=models.CharField(max_length=10),
        ),
    ]
