# Generated by Django 3.2 on 2024-08-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_location_routemetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routemetrics',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routemetrics',
            name='max_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routemetrics',
            name='max_duration_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routemetrics',
            name='min_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routemetrics',
            name='min_duration_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
