# Generated by Django 3.2 on 2024-08-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20240816_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routemetrics',
            name='distance_km',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routemetrics',
            name='max_cost',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routemetrics',
            name='max_duration_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='routemetrics',
            name='min_cost',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routemetrics',
            name='min_duration_hours',
            field=models.IntegerField(),
        ),
    ]
