# Generated by Django 3.2 on 2024-08-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_routemetrics_transport_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='status',
            field=models.BooleanField(choices=[(True, 'true'), (False, 'false')], default=True),
        ),
        migrations.AlterField(
            model_name='transportreq',
            name='status',
            field=models.BooleanField(choices=[(True, 'true'), (False, 'false')], default=True),
        ),
    ]
