# Generated by Django 3.2 on 2024-08-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_auto_20240817_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cost_per_one_ton', models.PositiveIntegerField()),
                ('max_cost_per_one_ton', models.PositiveIntegerField()),
                ('min_cost_per_one_km', models.PositiveIntegerField()),
                ('max_cost_per_one_km', models.PositiveIntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
