# Generated by Django 3.2 on 2024-08-17 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportreq',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_requests', to='transport.location'),
        ),
        migrations.AlterField(
            model_name='transportreq',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_requests', to='transport.location'),
        ),
    ]
