# Generated by Django 5.1 on 2024-09-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_auto_20240817_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transport',
            name='status',
            field=models.BooleanField(choices=[(True, 'true'), (False, 'false')], default=False),
        ),
    ]
