# Generated by Django 5.1 on 2024-09-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_transport_is_successful_alter_transport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportreq',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
    ]
