# Generated by Django 5.1 on 2024-09-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_transportreq_is_successful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportreq',
            name='status',
            field=models.BooleanField(choices=[(True, 'true'), (False, 'false')], default=False),
        ),
    ]
