# Generated by Django 5.1 on 2024-08-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divar', '0002_attributevalue_alter_divarattribute_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['name'], 'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ['value'], 'verbose_name': 'Attribute Value', 'verbose_name_plural': 'Attribute Values'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='divar',
            options={'ordering': ['-created_time'], 'verbose_name': 'Divar', 'verbose_name_plural': 'Divars'},
        ),
        migrations.AlterModelOptions(
            name='divarattribute',
            options={'verbose_name': 'Divar Attribute', 'verbose_name_plural': 'Divar Attributes'},
        ),
        migrations.AlterModelOptions(
            name='divarimage',
            options={'verbose_name': 'Divar Image', 'verbose_name_plural': 'Divar Images'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='divar/category/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='divarimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='divar/images/%Y/%m/%d/'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='divarattribute',
            unique_together={('divar', 'attribute')},
        ),
    ]
