# Generated by Django 5.1 on 2024-09-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_payment_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='num_bids',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
