# Generated by Django 5.1 on 2024-09-06 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_payment_num_bids'),
        ('transport', '0014_transportreq_is_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transportreq'),
        ),
    ]
